### ISSUE TITLE
7-5. JPA

### ISSUE THREAD

**Issue by qorwlalsjimin** [qorwlalsjimin/hello-spring#25]
JDBC template의 반복 코드 해결, SQL query를 Spring이 만들어서 실행해준다

**Comment by qorwlalsjimin** [comment]
## 환경 마련
1. Gradle 추가
`implementation 'org.springframework.boot:spring-boot-starter-data-jpa'`

2. application.properties 추가
```
//h2 DB
spring.datasource.url =  jdbc:h2:tcp://localhost/~/test
spring.datasource.driver-class-name = org.h2.Driver
spring.datasource.username=sa

//jpa
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto=none //자동 테이블 생성 끄기
```

**Comment by qorwlalsjimin** [comment]
## 실제 사용
`main/java/hello/hellospring/domain/Member`

1. @Entity 
```java
@Entity 
public class Member {
```
JPA가 관리하는 Entity 클래스임을 지정

2. @Id와 @Column
```java
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) //IDENTITY: DB가 알아서 생성해주는 값
    private Long id; //시스템에서 사용자를 식별하기 위해 지정

    @Column(name = "name")
    private String name; //사용자 이름
```
- @Id :  값을 구별할 수 있는 식별 column 역할. 
- @Column(name="컬럼명") :  사용자가 직접 만든 column과 매핑

**Comment by qorwlalsjimin** [comment]
## @Transactional
`main/java/hello/hellospring/service/MemberService.java`
JPA는 join할때 항상 Transactional 안에서 실행되어야 한다

**Comment by qorwlalsjimin** [comment]
## HibernateException 에러
```
Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:100) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:54) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:138) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:272) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	... 33 common frames omitted
```

### 해결 방법
application.properties 파일에
`spring.jpa.database=h2` 추가

**Comment by qorwlalsjimin** [comment]
## Repository 조립
### 1. EntityManager 객체 주입받기
```java
private EntityManager em;

    @Autowired
    public SpringConfig(EntityManager em) {
        this.em = em;
    }
```
### 2. JpaMemberRepository 객체 반환하기
```java
 @Bean
    public MemberRepository memberRepository(){
        return new JpaMemberRepository(em);
    }
```
